config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :brands
  resources :categories
  resources :reviews
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/home', to: 'brands#index'
  get '/menu', to: 'pages#menu'
  get '/about', to: 'pages#about'
  get '/products', to: 'products#index'
  get '/about', to: 'pages#about', as: 'about_page'
  get '/data_collection', to: 'data#index', as: 'data_collection'
  get 'brands', to: 'brands#index'
  get '/categories', to: 'categories#index'
  get '/reviews', to: 'reviews#index', as: 'all_reviews'
  get '/users', to: 'users#index', as: 'all_users'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
 has_many :products

#Validations
validates :name, length: { minimum: 2, maximum: 50 }
validates :brand_code, format: { with: /\A[a-zA-Z]+\z/, message: "should only contain letters" }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

#Validation
 validates :name, presence: true
 validates :name, format: { with: /\A[a-zA-Z\s]+\z/, message: "should only contain letters and spaces" }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  belongs_to :category
  has_many :reviews

#Validation
  validates :name, length: { minimum: 3, maximum: 50 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/models/review.rb
class Review < ApplicationRecord
  attribute :text, :string
  belongs_to :product

#Validation
  validates :content, length: { minimum: 10, maximum: 500 }
end

app/models/user.rb
class User < ApplicationRecord

#Validation
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    if params[:search].present?
      @brands = Brand.where("name LIKE ?", "%#{params[:search]}%")
    else
      @brands = Brand.where.not(name: nil, brand_code: nil)
    end
    @brands = @brands.page(params[:page]).per(15) # Change '15' to the desired number of brands per page
  end

  def show
    @brand = Brand.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  def show
    @category = Category.find(params[:id])
  end
  def index
    @categories = Category.page(params[:page]).per(15) # Change '10' to the desired number of brands per page
  end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  def index
    @products = Product.all
    @brands = Brand.all
    @categories = Category.all
    @reviews = Review.all
    @users = User.all
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def menu
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if params[:search]
      @products = Product.where("name LIKE ?", "%#{params[:search]}%").page(params[:page]).per(15)
    else
      @products = Product.page(params[:page]).per(15)
    end
  end
  def show
    @product = Product.find(params[:id])
    @category = @product.category
    @brand = @product.brand
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.page(params[:page]).per(15)
  end

  def show
    @review = Review.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:search].present?
      @users = User.where("name LIKE ?", "%#{params[:search]}%")
    else
      @users = User.all
    end
    @users = @users.page(params[:page]).per(15) # Change '15' to the desired number of users per page
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/data/index.html.erb
<h1>Products</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Brand</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.brand.name %></td>
        <td><%= product.category.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Brands</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand Code</th>
    </tr>
  </thead>
  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= brand.brand_code %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Categories</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Reviews</h1>
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Product</th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.content %></td>
        <td><%= review.product.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Users</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Product</th>
      <th>Created At</th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to review.content, review_path(review) %></td>
        <td><%= review.product.name %></td>
        <td><%= review.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<footer>
<%= paginate @reviews %>
</footer>

app/views/reviews/show.html.erb
<h1>Review Details</h1>
<p><strong>Content:</strong> <%= @review.content %></p>
<p><strong>Product:</strong> <%= link_to @review.product.name, @review.product %></p>