config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :brands
  resources :categories
  resources :reviews
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/home', to: 'brands#index'
  get '/menu', to: 'pages#menu'
  get '/about', to: 'pages#about'
  get '/products', to: 'products#index'
  get '/about', to: 'pages#about', as: 'about_page'
  get '/data_collection', to: 'data#index', as: 'data_collection'
  get 'brands', to: 'brands#index'
  get '/categories', to: 'categories#index'
  get '/reviews', to: 'reviews#index', as: 'all_reviews'
  get '/users', to: 'users#index', as: 'all_users'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
 has_many :products

#Validations
validates :name, length: { minimum: 2, maximum: 50 }
validates :brand_code, format: { with: /\A[a-zA-Z]+\z/, message: "should only contain letters" }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

#Validation
 validates :name, presence: true
 validates :name, format: { with: /\A[a-zA-Z\s]+\z/, message: "should only contain letters and spaces" }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  belongs_to :category
  has_many :reviews

#Validation
  validates :name, length: { minimum: 3, maximum: 50 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/models/review.rb
class Review < ApplicationRecord
  attribute :text, :string
  belongs_to :product

#Validation
  validates :content, length: { minimum: 10, maximum: 500 }
end

app/models/user.rb
class User < ApplicationRecord

#Validation
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    if params[:search].present?
      @brands = Brand.where("name LIKE ?", "%#{params[:search]}%")
    else
      @brands = Brand.where.not(name: nil, brand_code: nil)
    end
    @brands = @brands.page(params[:page]).per(15) # Change '15' to the desired number of brands per page
  end

  def show
    @brand = Brand.find(params[:id])
  end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  def index
    @products = Product.all
    @brands = Brand.all
    @categories = Category.all
    @reviews = Review.all
    @users = User.all
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def menu
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.page(params[:page]).per(15)
  end

  def show
    @review = Review.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:search].present?
      @users = User.where("name LIKE ?", "%#{params[:search]}%")
    else
      @users = User.all
    end
    @users = @users.page(params[:page]).per(15) # Change '15' to the desired number of users per page
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MakeupProducts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Menu', menu_path %></li>
    <!-- Add more menu items as needed -->
  </ul>
</nav>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Project</h1>
<p>This is the about page content.</p>
<p>ERD diagram</p>
<img src="/assets/project_erd.drawio.png" alt="ERD Diagram">

app/views/pages/home.html.erb
<h1>Welcome to the Makeup Products Application</h1>
<p>Discover the latest trends and enhance your beauty with our wide range of makeup products.</p>
<ul>
<li><%= link_to 'Products', products_path %></li>
</ul>
<p>Explore high-quality cosmetics, skincare, fragrances, and more from top brands.</p>
<ul>
<li><%= link_to 'Brands', brands_path %></li>
</ul>
<p>Whether you are a makeup enthusiast, a professional artist, or simply looking to enhance your everyday look, we have everything you need to express your unique style with the help of different categories of product.</p>
<ul>
<li><%= link_to 'Categories', categories_path %></li>
</ul>
<p>Stay updated with the hottest beauty releases, read product reviews, and find your holy grail makeup essentials.</p>
<ul>
<li><%= link_to 'Reviews', reviews_path %></li>
</ul>
<p>Get to know about some of our satisfied customers</p>
<ul>
<li><%= link_to 'Users', users_path %></li>
</ul>

app/views/pages/menu.html.erb
<h1>Menu</h1>

<ul>
  <li><%= link_to 'Brands', brands_path %></li>
  <li><%= link_to 'Categories', categories_path %></li>
  <li><%= link_to 'Reviews', reviews_path %></li>
  <li><%= link_to 'Products', products_path %></li>
  <li><%= link_to 'Users', users_path %></li>
</ul>